namespace backendORCinverisones.Application.DTOs.Products;

public class AutoGeneratedCodesDto
{
    public string Codigo { get; set; } = string.Empty;
    public string CodigoComer { get; set; } = string.Empty;
}
